// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SESOPtracker.Data;

#nullable disable

namespace SESOPtracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250324163911_Create Tables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SESOPtracker.Models.Entities.Equipamento", b =>
                {
                    b.Property<string>("patrimonio")
                        .HasColumnType("TEXT");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataCriacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("item")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("sala")
                        .HasColumnType("INTEGER");

                    b.Property<string>("setor")
                        .HasColumnType("TEXT");

                    b.Property<int>("situacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("patrimonio");

                    b.HasIndex("sala");

                    b.HasIndex("situacao");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("SESOPtracker.Models.Entities.Historico", b =>
                {
                    b.Property<int>("historicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dataAlteracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("importante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("patrimonio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("situacaoAtual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("historicoId");

                    b.HasIndex("patrimonio");

                    b.HasIndex("situacaoAtual");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("SESOPtracker.Models.Entities.Sala", b =>
                {
                    b.Property<int>("salaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("local")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("salaId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("SESOPtracker.Models.Entities.Situacao", b =>
                {
                    b.Property<int>("situacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("situacaoId");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("SESOPtracker.Models.Entities.Equipamento", b =>
                {
                    b.HasOne("SESOPtracker.Models.Entities.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("sala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SESOPtracker.Models.Entities.Situacao", "Situacao")
                        .WithMany()
                        .HasForeignKey("situacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Situacao");
                });

            modelBuilder.Entity("SESOPtracker.Models.Entities.Historico", b =>
                {
                    b.HasOne("SESOPtracker.Models.Entities.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("patrimonio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SESOPtracker.Models.Entities.Situacao", "Situacao")
                        .WithMany()
                        .HasForeignKey("situacaoAtual")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Situacao");
                });
#pragma warning restore 612, 618
        }
    }
}
